#+ endpoint: https://movies.abes.fr/proxy/wdqs/bigdata/namespace/wdq/sparql?
#+ endpoint_in_url: False
#+ description: La date de début d'habilitation doit être >= à la date de création de l'établissement. La date de fin d'habilitation doit être <= à la date de suppression de l'établissement.

PREFIX wdt: <https://movies.abes.fr/prop/direct/>
PREFIX wd: <https://movies.abes.fr/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX p: <https://movies.abes.fr/prop/>
PREFIX pq: <https://movies.abes.fr/prop/qualifier/>

SELECT DISTINCT ?etab ?habiliatation ?probleme ?date ?date_habilitation WHERE {
  {
    ?etab p:P22 ?habiliatation;
      wdt:P10 ?date. # date de création
    
    ?habiliatation pq:P12 ?date_habilitation.
    BIND("Le début d'habilitation est inférieur à la date de création de l'établissement" AS ?probleme)
    FILTER(?date_habilitation < ?date)
  }
  UNION
  {
    ?etab p:P22 ?habiliatation;
      wdt:P54 ?date. # date de suppression
    
    ?habiliatation pq:P5 ?date_habilitation.
    BIND("La fin d'habilitation est supérieure à la date de suppression de l'établissement" AS ?probleme)
    FILTER(?date_habilitation > ?date)
  }
}
