#+ endpoint_in_url: False
#+ description: Liste l'ensemble des indentifiants dans movies pour chaque entité;

#+ endpoint_in_url: False
#+ description: Liste l'ensemble des indentifiants;

PREFIX wdt: <https://movies.abes.fr/prop/direct/>
PREFIX wd: <https://movies.abes.fr/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX p: <https://movies.abes.fr/prop/>
PREFIX pq: <https://movies.abes.fr/prop/qualifier/>

SELECT * WHERE {
  OPTIONAL {?org wdt:P7 ?siren.}
  OPTIONAL {?org wdt:P8 ?siren.}
  OPTIONAL {?org wdt:P30 ?code_uai.}
  OPTIONAL {?org wdt:P3 ?code_etab.}
  OPTIONAL {?org wdt:P64 ?identifiant_cnrs.}
  OPTIONAL {?org wdt:P65 ?identifiant_cti.}
  OPTIONAL {?org wdt:P63 ?identifiant_ed.}
  OPTIONAL {?org wdt:P59 ?identifiant_eter.}
  OPTIONAL {?org wdt:P71 ?identifiant_fundig_data.}
  OPTIONAL {?org wdt:P62 ?identifiant_grid.}
  OPTIONAL {?org wdt:P34 ?identifiant_hal.}
  OPTIONAL {?org wdt:P35 ?identifiant_idref.}
  OPTIONAL {?org wdt:P68 ?identifiant_isil.}
  OPTIONAL {?org wdt:P70 ?identifiant_isni.}
  OPTIONAL {?org wdt:P36 ?identifiant_paysage.}
  OPTIONAL {?org wdt:P69 ?identifiant_orgref.}
  OPTIONAL {?org wdt:P66 ?identifiant_pia.}
  OPTIONAL {?org wdt:P33 ?identifiant_rnsr.}
  OPTIONAL {?org wdt:P38 ?identifiant_scanr.}
  OPTIONAL {?org wdt:P72 ?identifiant_viaf.}
}
