#+ endpoint: https://movies.abes.fr/proxy/wdqs/bigdata/namespace/wdq/sparql?
#+ endpoint_in_url: False
#+ description: Pour un identifiant donnée, retourne la liste des autres identifiants connus pour une entité.

PREFIX wdt: <https://movies.abes.fr/prop/direct/>
PREFIX wd: <https://movies.abes.fr/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX p: <https://movies.abes.fr/prop/>
PREFIX pq: <https://movies.abes.fr/prop/qualifier/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?org ?ids WHERE {
  ?org skos:altLabel ?id.
  
  FILTER(?_id = STR(?id)).
  
  ?org skos:altLabel ?ids.
    
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
