#+ endpoint: https://movies.abes.fr/proxy/wdqs/bigdata/namespace/wdq/sparql?
#+ endpoint_in_url: False
#+ description: Liste les ascendants et les déscendants d'un établissement à partir de son code etablissement. Recherche également le ou les établissements de ratachement (pour le premier établissement seulement)

PREFIX wdt: <https://movies.abes.fr/prop/direct/>
PREFIX wd: <https://movies.abes.fr/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX p: <https://movies.abes.fr/prop/>
PREFIX pq: <https://movies.abes.fr/prop/qualifier/>

SELECT DISTINCT ?orgLabel ?code_etablissement WHERE {
  ?etab wdt:P9 ?_codeEtab.

  # recherche de manière récursive les déscendants et ascendants et l'établissement d'appartenance
  ?etab (wdt:P6*/wdt:P4*)* | wdt:P17 ?org.
  
  ?org wdt:P47 [wdt:P53* wd:Q8];
       wdt:P9 ?code_etablissement.
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
