#+ endpoint: https://movies.abes.fr/proxy/wdqs/bigdata/namespace/wdq/sparql?
#+ endpoint_in_url: False
#+ description: Cette requête permet de trouver le ou les successeurs d'un établissement habilité à délivrer le doctorat

PREFIX wdt: <https://movies.abes.fr/prop/direct/>
PREFIX wd: <https://movies.abes.fr/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX p: <https://movies.abes.fr/prop/>
PREFIX pq: <https://movies.abes.fr/prop/qualifier/>

SELECT DISTINCT ?codeEtab ?codeEtabCible WHERE {
  ?etab wdt:P9 ?_codeEtab.
  
  # On renvoie le code etab si il est présent dans la base. (En cas de mauvais code etab ça peut servir).
  ?etab wdt:P9 ?codeEtab. 
  
  # Cas de figure 1 : L’établissement A est habilité en propre à délivrer le doctorat.
  # Ex (au 21/03/25) :  BORD est habilité à délivrer le doctorat.
  
  # Cas de figure 2 : L’établissement A est remplacé par l’établissement B. L’établissement A disparaît et transfère son habilitation doctorale à l’établissement B (est bénéficiaire de).
  # Ex (au 21/03/25) :  STR1 a disparu et a transféré son habilitation doctorale à STRA.
  
  # Cas de figure 6 : L'établissement A a disparu et a transféré son habilitation doctorale à plusieurs établissements B, C et D (il y a donc plusieurs bénéficiaires). C’est le cas des scissions d'établissements.
  # Ex (au 21/03/25) : LYSE a transféré son habilitation doctorale à LYO1, LYO2, LYO3, STET, ISAL, ENSL, ECDL, EMSE, ENTP
  OPTIONAL {
    ?etab p:P22 ?hab. # Récupération de l'habilitation
      
    ?hab <https://movies.abes.fr/prop/statement/P22> wd:Q20; # en cas de transfert
         pq:P1 ?beneficiaire.

    FILTER(NOT EXISTS { ?beneficiaire wdt:P54 ?date_suppression. })
    
    ?beneficiaire wdt:P9 ?codeEtabCible.
    ?etabCible wdt:P9 ?codeEtabCible.
  }
  
  # Cas de figure 3 : L’établissement A reste en vie, mais délègue son habilitation doctorale à l’établissement B (est délégataire de).
  # Ex (au 21/03/25) : EVRY délègue son habilitation doctorale à UPAS.
  
  # Cas de figure 5 : L’établissement A a délégué son habilitation doctorale à l’établissement B (est délégataire de) puis a transféré son habilitation à l’établissement C (est bénéficiaire de)
  # Ex (au 21/03/25) : DIJO a délégué son habilitation doctorale à UBFC puis a transféré son habilitation doctorale à UBEU.
  OPTIONAL {
    ?etab p:P22 ?hab. # Récupération de l'habilitation
      
    ?hab <https://movies.abes.fr/prop/statement/P22> wd:Q18; # en cas de délégation
         pq:P2 ?beneficiaire.    
            
    FILTER(NOT EXISTS { ?beneficiaire wdt:P54 ?date_suppression. })
    
    ?beneficiaire wdt:P9 ?codeEtabCible.
    ?etabCible wdt:P9 ?codeEtabCible.         
  }
  
  # Cas de figure 4 : L’établissement A est remplacé par l’établissement B. L’établissement A disparaît et transfère son habilitation doctorale à l’établissement B (est bénéficiaire de). 
  # MAIS, l’établissement B disparaît lui aussi et transfère son habilitation doctorale à l’établissement C (est bénéficiaire de).
  # Ex (au 21/03/25) : GREN a transféré son habilitation doctorale à GREA qui a transféré son habilitation doctorale à GRAL.
  OPTIONAL {
    ?etab p:P22 ?hab. # Récupération de l'habilitation
      
    ?hab <https://movies.abes.fr/prop/statement/P22> wd:Q20; # en cas de transfert
         pq:P1 ?beneficiaire.

    ?beneficiaire wdt:P54 ?date_suppression.
    
    OPTIONAL {
    ?beneficiaire p:P22 ?hab2. # Récupération de l'habilitation
      
    ?hab2 <https://movies.abes.fr/prop/statement/P22> wd:Q20; # en cas de transfert
         pq:P1 ?beneficiaire2.
    
    ?beneficiaire2 wdt:P9 ?codeEtabCible.
    ?etabCible wdt:P9 ?codeEtabCible.
    }    
  }
}
