
#+ endpoint: https://movies.abes.fr/proxy/wdqs/bigdata/namespace/wdq/sparql?
#+ endpoint_in_url: False
#+ description: Liste les habilitations doctorales d'un établissement

PREFIX wdt: <https://movies.abes.fr/prop/direct/>
PREFIX wd: <https://movies.abes.fr/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX p: <https://movies.abes.fr/prop/>
PREFIX pq: <https://movies.abes.fr/prop/qualifier/>
PREFIX pqv: <https://movies.abes.fr/prop/qualifier/value/>

SELECT ?etabLabel ?debut ?fin WHERE {
  ?etab wdt:P9 ?_codeEtab;
     p:P22 ?habiliatation;
     wdt:P22 wd:Q19.
  
  OPTIONAL {
    ?habiliatation pqv:P12/wikibase:timeValue ?debut.
  }
      
  OPTIONAL {?habiliatation pqv:P20/wikibase:timeValue ?fin}
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
